### ISSUE TITLE
Crashes with "Cannot read property 'wait' of undefined at hld_Debugger.wait"

### ISSUE THREAD

**Issue by Gama11** [ncannasse/vscode_hl#6]
With #4 and #5 worked around, the debugger crashes with the following:

![](https://i.imgur.com/mhh7Vx0.png)

Launch config:

```json
{
	"name": "HashLink",
	"type": "hl",
	"request": "launch",
	"preLaunchTask": "HL/JIT (Debug)",
	"hxml": "buildHL.hxml",
	"cwd": "${workspaceRoot}"
}
```

`buildHL.hxml`

```
build.hxml
-hl export/run.hl
```

`build.hxml`

```
-debug
-D dump=pretty

-cp source
-main Main
```

**Comment by ncannasse** [comment]
Could you check that the Debug VSCode output ? 
Do you have "connected" displayed there?

**Comment by Gama11** [comment]
```
0> HLAdapter.hx:38: initialize
0> HLAdapter.hx:54: launch
0> HLAdapter.hx:175: start process
0> HLAdapter.hx:224: load module
0> HLAdapter.hx:227: connecting
Could not initialize debugger
```

**Comment by Gama11** [comment]
Also, the dev console has a more complete stack trace:

```
Uncaught Error: TypeError: Cannot read property 'mainThread' of undefined
    at HLAdapter.threadsRequest (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\hladapter.js:420:58)
    at HLAdapter.DebugSession.dispatchRequest (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\node_modules\vscode-debugadapter\lib\debugSession.js:439:22)
    at HLAdapter.ProtocolServer._handleData (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
    at HLAdapter.threadsRequest (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\hladapter.js:420:58)
    at HLAdapter.DebugSession.dispatchRequest (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\node_modules\vscode-debugadapter\lib\debugSession.js:439:22)
    at HLAdapter.ProtocolServer._handleData (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Jens\.vscode\extensions\HaxeFoundation.haxe-hl-0.1.0\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2535:516
    at Object.v [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:147:170)
    at Object.enter (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:150:418)
    at n.Class.derive._oncancel._run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:719)
    at n.Class.derive._oncancel._error (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:236)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2344:409
    at b.e.dispatch (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2345:753)
    at b.e.handleData (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2345:261)
    at Socket.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2344:269)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by ncannasse** [comment]
The error `Could not initialize debugger` is the cause.
Here's what the code does:

```haxe
if( !dbg.connect("127.0.0.1", debugPort) || !dbg.init(new hld.NodeDebugApi(proc.pid, dbg.is64)) ) {
    sendToOutput("Could not initialize debugger");
    proc.kill("SIGINT");
    return;
}
```

So either for some reason the application has not started, or the socket cannot be accessed, or we cannot attach the debugger to it.

Could you try to add some traces and tell me what's wrong ? (hladapter.js line ~290)

**Comment by ncannasse** [comment]
I've added more verbose error log. When trying the debugger I also got a first "could not connect" error, but then after restart it worked well, not sure what's causing this. Maybe we need to wait a bit between hl process start and socket connection.

**Comment by Gama11** [comment]
Ok, I've switched from the marketplace version to a dev build, now I get this output instead:

```
0> src/HLAdapter.hx:38: initialize
0> src/HLAdapter.hx:54: launch
0> src/HLAdapter.hx:175: start process
0> src/HLAdapter.hx:247: load module
0> src/HLAdapter.hx:250: connecting
ERROR : ReferenceError: sys is not defined
```

And no more error notification or error in the dev console. Does that tell you anything?

**Comment by ncannasse** [comment]
Looks like you need to upgrade your hxnodejs ;)

**Comment by ncannasse** [comment]
ok ! back to the original issue then... 
Can you try adding a sleep before the dbg.connect ?

**Comment by Gama11** [comment]
That doesn't make any difference for me, even with `Sys.sleep(10);`.

**Comment by Gama11** [comment]
Ok, we figured it out on Slack. I had a `hl.bat` (which calls `hl.exe`) in my PATH rather than `hl.exe` itself, which the debugger didn't like.

Working now. \o/

![](https://i.imgur.com/Sf42umo.png)
